### ISSUE TITLE
Flaskのバージョンについて

### ISSUE THREAD

**Issue by shinriyo** [chaingng/shoeisha_serverless_python_tutorial#2]
P108に
```
python manage.py init_db
```
とありますが、
```
Flask-Script: from flask._compat import text_type ModuleNotFoundError: No module named 'flask._compat'
```
のエラーが出ます。

P30のように以下のコマンドだと2.xが入ってしまいます。
```
pipenv install "Flask"
```

https://stackoverflow.com/questions/67538056/flask-script-from-flask-compat-import-text-type-modulenotfounderror-no-module
のstackoverflowのように「pipenv install "Flask==1.1.4"」にするか、
`Pipfile.lock`のFlaskに合わせてバージョン指定すると解決しました。
```
pipenv install "Flask==1.1.2"
```

**Comment by chaingng** [comment]
@shinriyo 
ありがとうございます。
ご指摘のとおりでして、Q&Aに記載させていただきました。

https://github.com/chaingng/shoeisha_serverless_python_tutorial#1flask-script%E3%81%8C%E3%82%A4%E3%83%B3%E3%82%B9%E3%83%88%E3%83%BC%E3%83%AB%E3%81%A7%E3%81%8D%E3%81%AA%E3%81%84
