### ISSUE TITLE
[Question] bashrcの意味

### ISSUE THREAD

**Issue by shinriyo** [chaingng/shoeisha_serverless_python_tutorial#5]
P157で以下のように`~/.bashrc`を作成しましたが、
https://github.com/chaingng/shoeisha_serverless_python_tutorial/blob/master/snippets/list9.7.txt

結局P175にて、
https://github.com/chaingng/shoeisha_serverless_python_tutorial/blob/master/snippets/list9.13.txt
のように`zappa_setting.json`に記載しているので使われない用に思えます。
ちなみに、devですが通常本番環境はとかproductionですが、本書でいうことの「本番」という事ですよね？

本書では結局`~/.bashrc`を呼び出すことがないように思えます。
ローカル環境で`python server.py`を実行したとき専用でしょうか？

**Comment by chaingng** [comment]
@shinriyo 
コメントありがとうございます。bashrcですが2つの理由で作成しております。

1つめは、ローカルで本番用データベースの作成コマンドを実行するためです。
2つめは、それぞれの環境で動作確認および切り分けしながらステップごとに進められるよう用意しました。

- ローカル環境でDyanmoDB localで動作確認
- ローカル環境で本番DynamoDBでの動作確認
- サーバレス環境で本番DynamoDBでの動作確認

問題があったときにどの環境まで正しく動作しているか切り分けたり、
コードをアップデートしたときに順に動作確認することで急に大きな問題が発生することを防いだり、
また本書の構成としてステップごとに学んでいただけるようにという意味もございます。

devについてはご指摘のとおりでして、
任意の名前をつけられますため運用方法によって名付けいただくのがよろしいかと思います。
（サーバレスの開発環境、ステージング、本番環境を用意してそれぞれ dev, staging, productionとつけるなど）
本書ではzappa config作成時のデフォルト名 `dev` をそのまま使用しております。


改めて貴重なご意見ありがとうございます。
Q&Aにも記載させていただくようにいたします。

**Comment by chaingng** [comment]
@shinriyo 
[README](https://github.com/chaingng/shoeisha_serverless_python_tutorial/blob/master/README.md#7-p157%E3%81%AEbashrc%E3%81%AE%E7%92%B0%E5%A2%83%E5%A4%89%E6%95%B0%E3%81%AFp175%E3%81%A7zappa_settingsjson%E3%81%A7%E8%A8%AD%E5%AE%9A%E3%81%97%E3%81%A6%E3%81%84%E3%82%8B%E3%81%AE%E3%81%A7%E4%B8%8D%E8%A6%81%E3%81%A7%E3%81%AF%E3%81%AA%E3%81%84%E3%81%8B)に記載させていただきましたので、closeさせていただきます。
