### ISSUE TITLE
ch.10-7 デプロイ時に502エラーとなる

### ISSUE THREAD

**Issue by shinriyo** [chaingng/shoeisha_serverless_python_tutorial#6]
ch.9-6 デプロイ時に502エラーとなる #1
と似た現象で以下のエラーが発生しました。

```
Error: Warning! Status check on the deployed lambda failed. A GET request to '/' yielded a 502 response code.
```

そのIssueと同じ原因かどうか`zappa_settings.json` のフォーマットを
https://jsonlint.com/ で確認しましたが、正しいフォーマットでした。

@R1nY1x1 さんのコメントされてた`zappa tail`のコマンドでエラー原因をみられるとのことなので、
確認したところ。

以下のエラーが記載されてました。
```
[ERROR] AttributeError: module 'bot' has no attribute 'app'
```

ちなみにP207のコマンドでは
```
zappa status dev
```
以下なのでデプロイ自体は成功してるようです。
```
Event Rule Name:      serverless-bot-dev-bot.run_bot
```

しかし、P208のコマンドでも実行はできました。
```
zappa invoke dev "bot.run_bot"
```

**Comment by chaingng** [comment]
@shinriyo 
コメントありがとうございます。
上記メッセージですがWarningのため動作には問題ございません。

Zappaのデフォルトでは、Webアプリケーションも動くことを想定しておりますため
エンドポイントが存在しない場合に上記のWarningが表示されますが、動作に問題はございません。

もしWarningを消したい場合は、Configにて以下の設定を加えることで表示されなくなります。

```
{
    "dev": {
        "apigateway_enabled": false,
       ....
    }
}
```

本書ではWarningを非表示にするための設定を追記することでチュートリアルが煩雑になることを防ぐため、
あえて注釈での説明のみにとどめておりました。

こちら、頂いた内容につきましてQ&Aにも記載させていただきます。

**Comment by chaingng** [comment]
こちらのQ&Aに記載させていただきましたので、closeさせていただきます。

https://github.com/chaingng/shoeisha_serverless_python_tutorial#5-10%E7%AB%A0%E3%81%AB%E3%81%A6zappa-deploy%E6%99%82%E3%81%ABerror-warning-status-check-on-the-deployed-lambda-failed-a-get-request-to--yielded-a-502-response-code-%E3%81%8C%E7%99%BA%E7%94%9F%E3%81%99%E3%82%8B%E3%81%8C%E5%8B%95%E4%BD%9C%E3%81%AB%E5%95%8F%E9%A1%8C%E3%81%AA%E3%81%84%E3%81%8B
