### ISSUE TITLE
ch.9-5 本番用テーブルの作成に失敗する場合は、AWS CLIの事前インストールが必要?

### ISSUE THREAD

**Issue by vlayusuke** [chaingng/shoeisha_serverless_python_tutorial#9]
p.177で、本番用のテーブルを作成する際に、config.pyの`SESSION_TYPE`の行を一旦コメントアウトして、

`python3 manager.py init_db`

を実行すると、

`botocore.exceptions.NoCredentialsError: Unable to locate credentials`

エラーが発生して認証情報が取得できないと怒られます。

この場合、私のケースでは、AWS CLIをインストール後に、

`aws configure`

を実行してから再度コマンドを実行することによって回避することができました。

誤っている箇所がありましたらご指摘ください。

開発環境
- MacBook Air (Retina, 13-inch, 2018)
- macOS Big Sur 11.6
- Python 3.8

**Comment by chaingng** [comment]
ご質問ありがとうございます。
macの例でございますが、`aws configure` でも、本文のとおり直接記載する場合でも `~/.aws/credentials` が更新されているとの認識です。

https://docs.aws.amazon.com/ja_jp/cli/latest/userguide/cli-configure-quickstart.html

手元の環境にて `aws configure` なしで動作確認がとれましたので、いったんcloseとさせていただきます。
またご不明点ありましたらissueを立てて頂けましたら幸いです。
